; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino, espidf
monitor_raw = yes
monitor_speed = 115200
build_flags = -Isrc/drivers
upload_port = /dev/cu.usbserial-0001
lib_deps = 
	olikraus/U8g2 @ ^2.34.22
	janelia-arduino/TMC2209
	adafruit/Adafruit seesaw Library@^1.7.9
